In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
arr=np.arange(10)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
import sys
S=range(1000)
print(sys.getsizeof(S))
D=np.arange(1000)
print(D.itemsize)
print(D.size*D.itemsize)

48
8
8000


In [ ]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
c=print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
my_list=list(range(10))
print(my_list)
print(type(my_list))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [ ]:
#boolean indexing
import numpy as np
a=np.arange(12).reshape(3,4)
print("a=\n",a)
b=a>4
print("b=\n",b)
a[b]=1
print("a=\n",a)

a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b=
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a=
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [ ]:
#boolean indexing with strings
import numpy as np
names=np.array(['bob','joe','will','bob','will','joe','joe'])
data=np.arange(28).reshape(7,4)
print(names)
print("names bool= \n",names == 'bob')
print("names == 'Bob' \n",data[names == 'bob'])
print("names == 'Bob' \n",data[names == 'bob'])
print("names == 'Bob',3 \n",data[names == 'bob', 3])

['bob' 'joe' 'will' 'bob' 'will' 'joe' 'joe']
names bool= 
 [ True False False  True False False False]
names == 'Bob' 
 [[ 0  1  2  3]
 [12 13 14 15]]
names == 'Bob' 
 [[ 0  1  2  3]
 [12 13 14 15]]
names == 'Bob',3 
 [ 3 15]


In [ ]:
# select all except bob
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28).reshape(7, 4)
print(data[names != 'Bob'])
print("\n",data[~(names == 'Bob')])
data[names != 'Bob']=-1
print("\ndata= \n",data)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]

 [[ 4  5  6  7]
 [ 8  9 10 11]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]

data= 
 [[ 0  1  2  3]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [12 13 14 15]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1 -1 -1]]


In [ ]:
import numpy as pandas
arr=np.arange(32).reshape(8,4)
print("arr=\n",arr)
print("\narr[[1, 5, 7, 2]]= \n",arr[[1, 5, 7, 2]])
print("\narr[[1, 5, 7, 2], [0, 3, 1, 2]]= \n",arr[[1, 5, 7, 2], [0, 3, 1, 2]])
print("\narr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]= \n",arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])
print("\n arr[[-3, -5, -7]]\n",arr[[-3, -5, -7]])
arr[[1, 5, 7, 2]] = 1
print("\narr= \n",arr)


arr=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

arr[[1, 5, 7, 2]]= 
 [[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

arr[[1, 5, 7, 2], [0, 3, 1, 2]]= 
 [ 4 23 29 10]

arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]= 
 [[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]

 arr[[-3, -5, -7]]
 [[20 21 22 23]
 [12 13 14 15]
 [ 4  5  6  7]]

arr= 
 [[ 0  1  2  3]
 [ 1  1  1  1]
 [ 1  1  1  1]
 [12 13 14 15]
 [16 17 18 19]
 [ 1  1  1  1]
 [24 25 26 27]
 [ 1  1  1  1]]


In [1]:
import numpy as np
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32
